#!/bin/bash -x
echo "###################################### tempest_run ######################################"

tempest_unit=`juju status --format=tabular | grep ^tempest/. | awk {'print $1'}`
action_id=`juju action do ${tempest_unit} run-tempest | sed -e 's/Action queued with id: //g'`

until juju action fetch $action_id | grep "status: completed"; do
    sleep 60
    echo "Waiting for tempest tests to finish..."
done

mkdir remote-logs
juju scp ${tempest_unit}:/var/lib/tempest/logs/* remote-logs
cat remote-logs/*
juju ssh ${tempest_unit} "sudo chmod 755 /var/lib/tempest/tempest-11.0.0/tempest/.testrepository/0"
juju scp ${tempest_unit}:/var/lib/tempest/tempest-11.0.0/tempest/.testrepository/0 tempest-subunit.log
subunit-1to2 | subunit2junitxml -o tempest-results.xml
